# Generated by Django 4.2.7 on 2023-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0002_delete_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoPedido', models.CharField(max_length=10)),
                ('Estado', models.CharField(max_length=255)),
                ('Precio', models.PositiveIntegerField()),
                ('Nombre_Productos', models.CharField(max_length=200)),
                ('Cantidad', models.CharField(max_length=50)),
            ],
        ),
    ]
