# Generated by Django 4.2.7 on 2023-11-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
