# Generated by Django 4.2.7 on 2023-11-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_pedido_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.pedido', unique=True)),
            ],
        ),
    ]
