# Generated by Django 4.2.7 on 2023-11-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_encarga_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='CodigoPedido',
        ),
    ]
