# Generated by Django 4.2.7 on 2023-11-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Nombre_Productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Productos',
            field=models.ManyToManyField(to='delivery.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='Cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='Nombre_Producto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.cliente')),
                ('NRC', models.CharField(max_length=15)),
                ('Empleados', models.IntegerField()),
                ('Propietario', models.CharField(max_length=15)),
            ],
            bases=('delivery.cliente',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delivery.cliente')),
                ('DNI', models.CharField(max_length=20)),
            ],
            bases=('delivery.cliente',),
        ),
        migrations.AlterField(
            model_name='encarga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.usuario', unique=True),
        ),
    ]
