# Generated by Django 4.2.7 on 2023-11-30 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_cliente_remove_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Direccion', models.CharField(max_length=255)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IBAN', models.CharField(max_length=25)),
                ('Mail', models.CharField(max_length=30)),
                ('Hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Worktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efficiency', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('deliveries', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
