# Generated by Django 4.2.7 on 2023-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_employee_rating_worktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Cantidad',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Nombre_Producto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Estado',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
