# Generated by Django 4.2.7 on 2023-11-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_remove_pedido_productos_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe', models.IntegerField()),
                ('Fecha', models.DateTimeField()),
                ('Destinatario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe', models.IntegerField()),
                ('Fecha', models.DateTimeField()),
                ('Emisor', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True),
        ),
        migrations.AddField(
            model_name='worktime',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.gasto', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.ingreso', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comunica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pedido', unique=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asigna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pedido', unique=True)),
            ],
        ),
    ]
