# Generated by Django 4.2.7 on 2023-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_gasto_ingreso_rating_empleado_worktime_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
