# Generated by Django 4.2.7 on 2023-12-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_employee_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emite',
            name='empleado',
        ),
        migrations.AddField(
            model_name='emite',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.pedido', unique=True),
        ),
    ]
