# Generated by Django 4.2.7 on 2023-12-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_remove_emite_empleado_emite_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='Destinatario',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='Emisor',
        ),
    ]
