# Generated by Django 4.2.7 on 2023-12-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_remove_gasto_destinatario_remove_ingreso_emisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='empleado',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True)),
            ],
        ),
    ]
