# Generated by Django 4.2.7 on 2023-12-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_schedule_worktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='empleado',
        ),
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=400)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True)),
            ],
        ),
    ]
