# Generated by Django 4.2.7 on 2023-12-14 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_remove_rating_empleado_generate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.rating', unique=True),
        ),
    ]
