# Generated by Django 4.2.7 on 2023-12-17 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.menu')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.employee', unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Estado',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('En Envío', 'En Envío'), ('Entregado', 'Entregado')], default='En Preparación', max_length=40),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='NRC',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Generate',
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante'),
        ),
    ]
