# Generated by Django 4.2.7 on 2023-12-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_menu_producto_rating_empleado_alter_employee_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Nombre_Producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='Precio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='delivery.DetallePedido', to='delivery.producto'),
        ),
    ]
