# Generated by Django 4.2.7 on 2023-12-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_pedido_latitud_pedido_longitud'),
    ]

    operations = [
    ]
