# Generated by Django 4.2.7 on 2023-12-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_auto_20231224_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante'),
        ),
    ]
