# Generated by Django 4.2.7 on 2023-12-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0027_pedido_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante'),
        ),
    ]
