# Generated by Django 4.2.7 on 2023-12-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0035_alter_detallepedido_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together=set(),
        ),
    ]
