# Generated by Django 4.2.7 on 2023-12-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0036_alter_detallepedido_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
