# Generated by Django 4.2.7 on 2023-12-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0037_alter_detallepedido_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comunica',
        ),
    ]
