# Generated by Django 4.2.7 on 2024-01-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0039_rename_estado_pedido_estado_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='productos',
            field=models.ManyToManyField(related_name='menus', to='delivery.producto'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='delivery.restaurante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
