# Generated by Django 4.2.7 on 2024-01-11 20:41

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0040_remove_menu_nombre_remove_restaurante_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(limit_choices_to={'menu__restaurante': delivery.models.Restaurante}, through='delivery.DetallePedido', to='delivery.producto'),
        ),
    ]
