# Generated by Django 4.2.7 on 2024-01-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0042_remove_menu_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='productos',
            field=models.ManyToManyField(related_name='menus', to='delivery.producto'),
        ),
    ]
