# Generated by Django 4.2.7 on 2024-01-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0043_menu_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio_total',
        ),
    ]
