# Generated by Django 4.2.7 on 2024-01-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0045_remove_employee_schedule_remove_worktime_deliveries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
