# Generated by Django 4.2.7 on 2024-01-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0045_ingreso_pedido_delete_emite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='Importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='Importe',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
