# Generated by Django 4.2.7 on 2024-01-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0046_alter_gasto_importe_alter_ingreso_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Apellidos',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
