# Generated by Django 4.2.7 on 2024-01-12 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0046_alter_rating_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='gasto_generado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_generador', to='delivery.gasto'),
        ),
    ]
