# Generated by Django 4.2.7 on 2024-01-12 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0048_remove_pedido_gasto_generado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emite',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='emite',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='gasto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='delivery.employee'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='gasto_generado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_generador', to='delivery.gasto'),
        ),
        migrations.DeleteModel(
            name='Asigna',
        ),
        migrations.DeleteModel(
            name='Emite',
        ),
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
