# Generated by Django 4.2.7 on 2024-01-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0048_remove_encarga_pedido_remove_encarga_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='empleado_asignado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='DNI',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.CreateModel(
            name='Asigna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pedido')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.employee')),
            ],
            options={
                'unique_together': {('trabajador', 'pedido')},
            },
        ),
    ]
