# Generated by Django 4.2.7 on 2024-01-13 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0049_remove_emite_ingreso_remove_emite_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='worktime',
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='delivery.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='gasto_generado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='delivery.gasto'),
        ),
        migrations.DeleteModel(
            name='Encarga',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
