# Generated by Django 4.2.7 on 2024-01-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0050_remove_schedule_worktime_pedido_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='worktime',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='worktime',
        ),
        migrations.AddField(
            model_name='worktime',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.employee'),
        ),
    ]
