# Generated by Django 4.2.7 on 2024-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0050_remove_employee_gasto_remove_pedido_gasto_generado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pedidos',
            field=models.ManyToManyField(blank=True, to='delivery.pedido'),
        ),
    ]
