# Generated by Django 4.2.7 on 2024-01-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0052_remove_worktime_employee_employee_worktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Hire_date',
        ),
    ]
