# Generated by Django 4.2.7 on 2024-01-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0052_pedido_repartidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pedidos',
        ),
        migrations.CreateModel(
            name='Encarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'pedido')},
            },
        ),
    ]
