# Generated by Django 4.2.7 on 2024-01-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0053_remove_employee_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='delivery.employee'),
        ),
    ]
