# Generated by Django 4.2.7 on 2024-01-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0054_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='longitud',
        ),
    ]
