# Generated by Django 4.2.7 on 2024-01-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0055_remove_employee_worktime_employee_worktimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gasto',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='worktimes',
        ),
        migrations.AddField(
            model_name='worktime',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktimes', to='delivery.employee'),
        ),
    ]
