# Generated by Django 4.2.7 on 2024-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0055_remove_pedido_latitud_remove_pedido_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('preparacion', 'En preparación'), ('envio', 'En envío'), ('entregado', 'Entregado')], default='En Preparación', max_length=40),
        ),
    ]
