# Generated by Django 4.2.7 on 2024-01-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0056_remove_employee_gasto_remove_employee_worktimes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gasto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.gasto'),
        ),
    ]
