# Generated by Django 4.2.7 on 2024-01-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0057_employee_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='delivery.restaurante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='delivery.menu'),
        ),
    ]
