# Generated by Django 4.2.7 on 2024-01-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0058_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('En Envío', 'En Envío'), ('Entregado', 'Entregado')], default='En Preparación', max_length=40),
        ),
    ]
