# Generated by Django 4.2.7 on 2024-01-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0058_alter_menu_restaurante_alter_producto_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='delivery.restaurante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.menu'),
        ),
    ]
