# Generated by Django 4.2.7 on 2024-01-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0059_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='delivery.restaurante'),
        ),
    ]
