# Generated by Django 5.0.1 on 2024-01-24 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0060_alter_menu_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='delivery.restaurante'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En Preparación', 'En preparación'), ('envio', 'En envío'), ('entregado', 'Entregado')], default='En Preparación', max_length=40),
        ),
    ]
