# Generated by Django 4.2.7 on 2024-01-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0060_gasto_comentario_ingreso_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Salario',
        ),
    ]
